name: Continuous Deployment

on:
  push:
    branches:
      - develop

jobs:
  deploy_staging:
    name: Staging Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: npm install
      run: |
        npm install
    - name: yarn test
      run: |
        yarn lint
      env:
        CI: true

    - name: yarn build
      run: |
        yarn run build --if-present

    - name: Add remote origin
      run: |
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
    - name: Deploy to Heroku
      run: |
        git push heroku HEAD:master -f
