name: Continuous Integration

on: [pull_request]

jobs:
  lint_build:
    name: Test Lint and build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: npm install
      run: |
        npm install
    - name: npm lint
      run: |
        npm run lint


    - name: npm build
      run: |
        npm run build

